
import "./globals.css";
import Headers from "@/components/headers/index";
import Footer from "@/components/footer/footer";

export const metadata = {
  title: "Spline Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  );
}
